site_name: Jerry J. Gu as Developer
site_url: https://jgujerry.github.io

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - Tools:
    - Cursor: tools/cursor.md
    - Tmux: tools/tmux.md

extra_css:
  - styles/extra.css
