site_name: Jerry J. Gu as a Developer
site_url: https://jgujerry.github.io

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - Cheatsheet:
    - Tools:
      - Cursor: cheatsheet/tools/cursor.md
      - Tmux: cheatsheet/tools/tmux.md
    - Databases:
      - PostgreSQL: cheatsheet/databases/postgresql.md
      
extra_css:
  - styles/extra.css
